### ISSUE TITLE
General Analytics

### ISSUE THREAD

**Issue by RileyDatLord** [RONTheCookie/discordboats.club#49]
Analytics for bots such as, times Invite button clicks, times Page viewed, etc

**Comment by RONTheCookie** [comment]
i already wanted to do this, thanks for making a issue (^:

**Comment by RONTheCookie** [comment]
need someone to do frontend, most of backend if not all is done. - maybe i'll wait for @jellz to come back from his vacation

**Comment by RONTheCookie** [comment]
Ganalytics isn't gonna do it, and we already have our own solution
