### ISSUE TITLE
Dark theme issues with add/edit bot

### ISSUE THREAD

**Issue by imalexok** [RONTheCookie/discordboats.club#63]
### Expected behaviour?
was expecting long description text in add/edit bot would be white

### Actual behaviour?
its black and you can barely see it

### Steps to reproduce?
- turn on dark theme
- try editing or adding a bot, then type in the long description box
- boom 💥 

### Any additional information?
picture:
![image](https://user-images.githubusercontent.com/32041075/40824799-caafa460-65b8-11e8-9e60-89405fc0090b.png)
its also incredibly annoying for dark theme users :(

**Comment by jellz** [comment]
@RONTheCookie made the dark theme as an extension, and afaik it's not fully supported
Hope your issue is fixed though 👍

**Comment by RONTheCookie** [comment]
odd

**Comment by imalexok** [comment]
this also doesn't happen with other fields like short description, only the long description is affected

**Comment by jellz** [comment]
The add bot and edit bot pages are messed up

**Comment by RONTheCookie** [comment]
i know why its doing it, ill fix it when i have more time.

**Comment by RONTheCookie** [comment]
you may need to use Ctrl+F5 to get the changes
