### ISSUE TITLE
Dark theme on profiles not working at all

### ISSUE THREAD

**Issue by ThatTonybo** [RONTheCookie/discordboats.club#74]
### Expected behaviour?
Dark theme would display properly, instead of light theme.

### Actual behaviour?
Light theme displays regardless of settings on the profile page.

### Steps to reproduce?
1. Turn on dark theme on any page.
2. Go to the profile page. [dark theme should disable]
3. Try turning dark theme on.
4. It'll stay light, regardless of settings.

### Any additional information?
[Example Page](https://discordboats.club/user/296044953576931328)
![image](https://user-images.githubusercontent.com/28176227/44436003-2d93d100-a5f6-11e8-9ed5-26033124cbc9.png)

**Comment by jellz** [comment]
Maybe because user profiles aren’t finished and they were never properly released?
